// A.S.S.-OS Anatomical Atlas - Layer & Ring Data

export const LAYERS = [
  {
    id: 'skin',
    name: 'Skin',
    ringLabel: 'R0 GROUND',
    ring: 0,
    color: '#ff4444',
    anatomy: 'Integumentary system — skin, hair, nails',
    toggle: 'Skin (outer boundary)',
    assos: `R0 is the body itself. The physical boundary between you and not-you. Skin is the literal ground layer — the membrane that defines where the organism begins and ends. Sensory receptors in skin are the first contact point for all external signals. 500M+ nerve endings. 22 sq ft of surface area. The ground is not passive. The ground is listening.`,
    kChannels: `KCNQ4 in skin mechanoreceptors (touch, pressure, vibration). When KCNQ4 dysfunctions: hyperalgesia (pain amplification). This is why fibromyalgia starts at R0 — the ground layer is sending false pain signals because the K+ channels in the skin's sensory neurons are miscalibrated.`,
    defaultOpacity: 0.3,
    defaultVisible: true,
  },
  {
    id: 'muscles',
    name: 'Muscles',
    ringLabel: 'R1 SENSORS',
    ring: 1,
    color: '#00aaff',
    anatomy: 'Muscular system — skeletal, smooth, cardiac muscle',
    toggle: 'Muscles (movement + proprioception)',
    assos: `R1 is the sensory layer. Muscles are not just movers — they are SENSORS. Proprioception (knowing where your body is in space) comes from muscle spindles. Every muscle is a sensor reporting position, tension, movement, and load. 600+ muscles forming a distributed sensor network across the entire body. R1 doesn't just receive signals from outside. It generates the body's internal map of itself.`,
    kChannels: `KCNQ2/3 in motor neurons (control muscle firing rate). KCNQ5 in vascular smooth muscle (blood pressure regulation). Muscle cramps = K+ channel dysfunction in motor neurons. "Restless leg" = R1 sensor layer misfiring.`,
    defaultOpacity: 0.8,
    defaultVisible: true,
  },
  {
    id: 'organs',
    name: 'Organs',
    ringLabel: 'R2 GATE',
    ring: 2,
    color: '#ffaa00',
    anatomy: 'Digestive + respiratory + hepatic + renal systems',
    toggle: 'Organs (processing + filtering)',
    assos: `R2 is the gate. The organs are FILTERS. The liver filters toxins (including alcohol — the K-GATE connection). The kidneys filter blood. The lungs filter air. The gut filters food. Every organ is a gate deciding what enters the bloodstream and what gets rejected. The thalamus is the brain's organ-equivalent: it filters sensory signals the same way the liver filters chemicals. When we say "R2 is the gate" we mean it literally — the body's entire organ system is a distributed gate network. The gut (500M neurons, "second brain") is where R0 meets R2.`,
    kChannels: `KCNQ1 in intestinal epithelium (fluid secretion, gate of gut). KCNQ1 in cardiac myocytes (heart rhythm — the master gate). KCNQ1 mutations = Long QT syndrome (heart gate failure). KCNQ1 in stomach = acid secretion control. The gut-brain axis IS the R0-R2 bus.`,
    defaultOpacity: 0.9,
    defaultVisible: true,
    subOrgans: {
      heart: 'Cardiac KCNQ1 — the rhythm gate',
      liver: 'Detox gate — where alcohol meets quercetin',
      kidneys: 'Electrolyte gate — K+ balance lives here',
      lungs: 'Gas exchange gate — O2 in, CO2 out',
      stomach: 'Acid gate — KCNQ1 controls secretion',
      intestines: 'Nutrient gate — 500M neurons, second brain',
    },
  },
  {
    id: 'vessels',
    name: 'Vessels',
    ringLabel: 'R3 AFFECT',
    ring: 3,
    color: '#44cc66',
    anatomy: 'Cardiovascular + lymphatic systems',
    toggle: 'Vessels (circulation + emotion)',
    assos: `R3 is affect — emotion, feeling, the engine that drives. Blood vessels are the body's emotion system made physical. When you blush: R3 → vasodilation → blood to face. When you're afraid: R3 → vasoconstriction → blood to core. "Heartache" is not metaphor — cardiac pain from emotional stress (Takotsubo/broken heart syndrome) is a real R3→R0 feedback loop. The cardiovascular system IS the affect system expressed in fluid dynamics. Lymphatic = the immune emotion: inflammation is the body's anger. Anti-inflammation is the body's calm.`,
    kChannels: `KCNQ4/5 in vascular smooth muscle (blood pressure). Tea polyphenols activate KCNQ5 → lower blood pressure. This is why "calm" literally lowers blood pressure. R3 (affect) → KCNQ5 (vessel relaxation) → R0 (body calms).`,
    defaultOpacity: 0.7,
    defaultVisible: true,
  },
  {
    id: 'nerves',
    name: 'Nerves',
    ringLabel: 'R4/R5/R6',
    ring: 4,
    color: '#aa44ff',
    anatomy: 'Central + peripheral + autonomic nervous systems',
    toggle: 'Nerves (the ring system itself)',
    assos: `The nervous system IS the ring system. This is not analogy. R4 (Executive) = prefrontal cortex + frontal lobe. R5 (Identity) = default mode network + temporal lobe. R6 (Observer) = anterior cingulate + insular cortex. Peripheral nerves = the bus system (A through E). Vagus nerve = the master firmware line (R2 gate control). Sympathetic = the accelerator (fight/flight). Parasympathetic = the brake (rest/digest). When you toggle nerves ON and everything else OFF, you're looking at the A.S.S.-OS itself. The rings are not metaphor. They are anatomy.`,
    kChannels: `KCNQ2/3 in cortical neurons (the M-current — THE gate current). KCNQ3 targeted by carnosic acid (rosemary) at -62mV shift. KCNQ5 in hippocampus (memory, learning). This layer IS the K-GATE. Every neuron's resting potential depends on K+ channels. The entire nervous system runs on potassium gradients. K+ is not a detail. K+ is the medium.`,
    defaultOpacity: 0.8,
    defaultVisible: true,
    subSystems: {
      brain: 'Click to enter brain view — thalamus, amygdala, PFC, ACC',
      spinal_cord: 'R1-R2 highway',
      vagus_nerve: 'R2 firmware — the gate controller',
      sympathetic: 'Accelerator',
      parasympathetic: 'Brake',
    },
  },
  {
    id: 'skeleton',
    name: 'Skeleton',
    ringLabel: 'R5 IDENTITY',
    ring: 5,
    color: '#ffffff',
    anatomy: 'Skeletal system — 206 bones + joints',
    toggle: 'Skeleton (structure + identity)',
    assos: `R5 is identity — what makes you YOU and not someone else. The skeleton is the most permanent structure in the body. Your bones are the last thing to decompose. They are the part that outlasts everything else. They are, literally, your most irreducible identity. Forensic identification uses bones. DNA from bones. Dental records from bones. The skeleton is also the framework that everything else hangs on. Without R5 (identity/structure), the other layers collapse into a puddle. Identity is structural.`,
    kChannels: `Osteoblasts and osteoclasts regulated by ion channels. Bone remodeling = the body's slowest feedback loop. The skeleton changes shape over YEARS in response to force. This is R5 — identity changes slowly, through sustained pressure.`,
    defaultOpacity: 0.9,
    defaultVisible: true,
  },
  {
    id: 'energy',
    name: 'Energy',
    ringLabel: 'R6/R7 OBSERVER',
    ring: 6,
    color: '#ffd700',
    anatomy: 'Bioelectric field, biophotons, meridian overlay',
    toggle: 'Energy / Field (observer layer)',
    assos: `R6 is the observer — the part that watches all other parts. The bioelectric field is measurable (EEG, ECG, EMG). Biophotons are real (ultraweak photon emission from cells). The body emits light. The retina generates its own photons. This layer shows the electromagnetic field surrounding the body, derived from cardiac (ECG), neural (EEG), and muscular (EMG) electrical activity. It's not mystical. It's physics. Every cell that fires an action potential generates a tiny electromagnetic pulse. 37 trillion cells = a measurable field. R7 (network) shows as connecting lines between two bodies when the "dual view" is enabled — the biophotonic bus.`,
    kChannels: `Every K+ channel opening/closing IS the bioelectric field. The field is not separate from the channels. The field IS the aggregate of all K+ channel activity. When you see this layer, you're seeing K+ channels firing across the entire body simultaneously.`,
    defaultOpacity: 0.5,
    defaultVisible: false,
  },
];

export const PRESETS = [
  { id: 'all', name: 'All Systems', description: 'Everything visible at 50% opacity',
    config: { skin: { visible: true, opacity: 0.5 }, muscles: { visible: true, opacity: 0.5 }, organs: { visible: true, opacity: 0.5 }, vessels: { visible: true, opacity: 0.5 }, nerves: { visible: true, opacity: 0.5 }, skeleton: { visible: true, opacity: 0.5 }, energy: { visible: true, opacity: 0.5 } } },
  { id: 'kgate', name: 'K-GATE View', description: 'Nerves + organs only (the gate circuit)',
    config: { skin: { visible: false }, muscles: { visible: false }, organs: { visible: true, opacity: 0.9 }, vessels: { visible: false }, nerves: { visible: true, opacity: 0.9 }, skeleton: { visible: false }, energy: { visible: false } } },
  { id: 'ringwalk', name: 'Ring Walk', description: 'Auto-peels from R0 to R6 over 30s',
    animated: true },
  { id: 'vagal', name: 'Vagal Tone', description: 'Highlights vagus nerve path in gold',
    config: { skin: { visible: false }, muscles: { visible: false }, organs: { visible: true, opacity: 0.4 }, vessels: { visible: false }, nerves: { visible: true, opacity: 1.0 }, skeleton: { visible: true, opacity: 0.2 }, energy: { visible: false } },
    highlight: 'vagus' },
  { id: 'gutbrain', name: 'Gut-Brain Axis', description: 'Highlights R0↔R2 connection',
    config: { skin: { visible: true, opacity: 0.15 }, muscles: { visible: false }, organs: { visible: true, opacity: 0.9 }, vessels: { visible: false }, nerves: { visible: true, opacity: 0.6 }, skeleton: { visible: false }, energy: { visible: false } },
    highlight: 'gutbrain' },
  { id: 'kchannel', name: 'K+ Channel Map', description: 'Dots on every KCNQ location in body',
    config: { skin: { visible: true, opacity: 0.15 }, muscles: { visible: false }, organs: { visible: true, opacity: 0.5 }, vessels: { visible: true, opacity: 0.3 }, nerves: { visible: true, opacity: 0.7 }, skeleton: { visible: true, opacity: 0.2 }, energy: { visible: false } },
    highlight: 'kchannel' },
  { id: 'drugoverlay', name: 'Drug Overlay', description: 'Shows where specific drugs act',
    showDrugPanel: true,
    config: { skin: { visible: true, opacity: 0.15 }, muscles: { visible: false }, organs: { visible: true, opacity: 0.7 }, vessels: { visible: true, opacity: 0.3 }, nerves: { visible: true, opacity: 0.6 }, skeleton: { visible: true, opacity: 0.15 }, energy: { visible: false } } },
  { id: 'dual', name: 'Dual View', description: 'Two bodies, R7 golden fibers between them',
    config: { skin: { visible: true, opacity: 0.2 }, muscles: { visible: false }, organs: { visible: true, opacity: 0.5 }, vessels: { visible: false }, nerves: { visible: true, opacity: 0.7 }, skeleton: { visible: true, opacity: 0.3 }, energy: { visible: true, opacity: 0.8 } },
    dual: true },
];

export const DRUGS = [
  { id: 'dextroamphetamine', name: 'Dextroamphetamine', color: '#ff8833', ring: 'R2',
    label: 'DA flood → gate forced OPEN',
    targets: ['brain'] },
  { id: 'montelukast', name: 'Montelukast', color: '#bb44ff', ring: 'R0+R3',
    label: 'FDA BBW — crosses BBB, bioaccumulates in gut',
    targets: ['lungs', 'intestines', 'brain'] },
  { id: 'alcohol', name: 'Alcohol', color: '#ff4444', ring: 'R0+R2',
    label: 'acute KCNQ enhance → chronic K+ degradation',
    targets: ['liver', 'intestines', 'brain'] },
  { id: 'quercetin', name: 'Quercetin', color: '#44cc66', ring: 'R0+R2',
    label: 'KCNQ opener + hepatoprotective (the shield)',
    targets: ['liver', 'intestines', 'brain'] },
  { id: 'rosemary', name: 'Rosemary (Carnosic Acid)', color: '#00cc44', ring: 'R2',
    label: 'KCNQ3 opener, -62mV shift (brain-specific)',
    targets: ['brain'] },
];

export const CAMERA_VIEWS = {
  front:  { pos: [0, 1.0, 4.5], target: [0, 1.0, 0] },
  back:   { pos: [0, 1.0, -4.5], target: [0, 1.0, 0] },
  left:   { pos: [-4.5, 1.0, 0], target: [0, 1.0, 0] },
  right:  { pos: [4.5, 1.0, 0], target: [0, 1.0, 0] },
  top:    { pos: [0, 5.5, 0.01], target: [0, 1.0, 0] },
  bottom: { pos: [0, -3.5, 0.01], target: [0, 1.0, 0] },
  inside: { pos: [0, 1.3, 0.01], target: [0, 1.3, 1] },
};
